version: '3.8'

services:
  rpc-balancer:
    build: 
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-dev}
    restart: unless-stopped